# Generated by Django 5.2.7 on 2025-10-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='sem',
            field=models.CharField(blank=True, choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem'), ('3rd Sem', '3rd Sem'), ('4th Sem', '4th Sem'), ('5th Sem', '5th Sem'), ('6th Sem', '6th Sem')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slipquestion',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slip',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20),
        ),
    ]
