# Generated by Django 5.2.7 on 2025-10-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMateApp', '0002_slip_sem_slipquestion_output_alter_slip_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipquestion',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
