# Generated by Django 5.2.7 on 2025-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMateApp', '0003_slipquestion_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='explore_topics/')),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('AI', 'AI'), ('Database', 'Database'), ('Cloud', 'Cloud'), ('Web Development', 'Web Development'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Humanities', 'Humanities'), ('Data Science', 'Data Science')], default='Programming', max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
