# Generated by Django 5.2.7 on 2025-10-22 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMateApp', '0006_communitythread_communityreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploretopic',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exploretopic',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
