# Generated by Django 5.2.7 on 2025-10-22 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusMateApp', '0007_alter_exploretopic_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
